config/routes.rb
Payslip::Application.routes.draw do
  resources :users do
    member do
      get 'salary', :action => :salary_slip
    end
  end

  resources :salaries

end

app/models/salary.rb
class Salary < ActiveRecord::Base
  belongs_to :user
  SALARY_URL = ""

  ROW_MAP = {
      "Name of Employee"=> "name",
      "Basic"=> "basic",
      "HRA"=> "hra",
      "Children \nAllow."=> "children_allowance",
      "Transport Allow."=> "transport_allowance",
      "Medical  Allow."=> "medical_allowance",
      "Tech. Research Allow."=> "tech_research_allowance",
      "Special Allow."=> "special_allowance",
      "Internet & Telephone"=> "internet_and_telephone",
      "PF Cont.by Emplyr."=> "pf_contribution_by_employer",
      "Leave Travel Allow."=> "leave_travel_allowance",
      "Gross Salary"=> "gross_salary",
      "TDS"=> "tds",
      "PF"=> "pf",
      "Advance"=> "advance",
      "Net Payable" => "net_payable"
  }

  def self.import_xls
    Salary.destroy_all # We only import one month at a time # Change to keep historical data

    require 'roo'

    s = Roo::Google.new(APP_CONFIG[:xls_key], {:user => APP_CONFIG[:username], :password => APP_CONFIG[:password]})

    s.default_sheet = s.sheets.first

    data = s.parse(:header_search => ['Basic'])

    data.shift
    data.pop

    data.each do |d|
      d.delete('S. No.') # This will delete all the information tht has not been mapped !
    end


    dat = data.collect {|d| Hash[d.map {|k, v| [Salary::ROW_MAP[k].to_sym, v] }]}

    dat.each do |d|
      d['user_id'] = User.find_by_name(d[:name].strip).id rescue nil

      Salary.create(d)
    end
  end
end

app/models/user.rb
require 'csv-mapper'

class User < ActiveRecord::Base
  has_one :salary
end

include CsvMapper

if(User.count == 0)
  results = import(Rails.root.join('doc', 'users.csv')) do
    map_to User # Map to the Person ActiveRecord class (defined above) instead of the default OpenStruct.
    after_row lambda{|row, user| user.save }  # Call this lambda and save each record after it's parsed.

    start_at_row 0
    [name, email, pan, designation, pf, joined_at]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salaries }
    end
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
    @salary = Salary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @salary }
    end
  end

  # GET /salaries/new
  # GET /salaries/new.json
  def new
    @salary = Salary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @salary }
    end
  end

  # GET /salaries/1/edit
  def edit
    @salary = Salary.find(params[:id])
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(params[:salary])

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render json: @salary, status: :created, location: @salary }
      else
        format.html { render action: "new" }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salaries/1
  # PUT /salaries/1.json
  def update
    @salary = Salary.find(params[:id])

    respond_to do |format|
      if @salary.update_attributes(params[:salary])
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy

    respond_to do |format|
      format.html { redirect_to salaries_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :set_user

  def set_user
    @user = User.find(params[:id]) if params and params[:id]
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  def salary_slip
    @salary = @user.salary
    render :layout => nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Payslip"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Payslip
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        -#.span3
        -#  .well.sidebar-nav
        -#    %ul.nav.nav-list
        -#      %li.nav-header Sidebar
        -#      %li= link_to "Link 1", "/path1"
        -#      %li= link_to "Link 2", "/path2"
        -#      %li= link_to "Link 3", "/path3"
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2014

app/views/salaries/_form.html.haml
= form_for @salary, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :basic, :class => 'control-label'
    .controls
      = f.text_field :basic, :class => 'text_field'
  .control-group
    = f.label :hra, :class => 'control-label'
    .controls
      = f.text_field :hra, :class => 'text_field'
  .control-group
    = f.label :children_allowance, :class => 'control-label'
    .controls
      = f.text_field :children_allowance, :class => 'text_field'
  .control-group
    = f.label :transport_allowance, :class => 'control-label'
    .controls
      = f.text_field :transport_allowance, :class => 'text_field'
  .control-group
    = f.label :medical_allowance, :class => 'control-label'
    .controls
      = f.text_field :medical_allowance, :class => 'text_field'
  .control-group
    = f.label :tech_research_allowance, :class => 'control-label'
    .controls
      = f.text_field :tech_research_allowance, :class => 'text_field'
  .control-group
    = f.label :special_allowance, :class => 'control-label'
    .controls
      = f.text_field :special_allowance, :class => 'text_field'
  .control-group
    = f.label :internet_and_telephone, :class => 'control-label'
    .controls
      = f.text_field :internet_and_telephone, :class => 'text_field'
  .control-group
    = f.label :pf_contribution_by_employer, :class => 'control-label'
    .controls
      = f.text_field :pf_contribution_by_employer, :class => 'text_field'
  .control-group
    = f.label :leave_travel_allowance, :class => 'control-label'
    .controls
      = f.text_field :leave_travel_allowance, :class => 'text_field'
  .control-group
    = f.label :gross_salary, :class => 'control-label'
    .controls
      = f.text_field :gross_salary, :class => 'text_field'
  .control-group
    = f.label :tds, :class => 'control-label'
    .controls
      = f.text_field :tds, :class => 'text_field'
  .control-group
    = f.label :pf, :class => 'control-label'
    .controls
      = f.text_field :pf, :class => 'text_field'
  .control-group
    = f.label :advance, :class => 'control-label'
    .controls
      = f.text_field :advance, :class => 'text_field'
  .control-group
    = f.label :net_payable, :class => 'control-label'
    .controls
      = f.text_field :net_payable, :class => 'text_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), salaries_path, :class => 'btn'

app/views/salaries/edit.html.haml
- model_class = Salary
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/salaries/index.html.haml
- model_class = Salary
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:basic)
      %th= model_class.human_attribute_name(:hra)
      %th= model_class.human_attribute_name(:children_allowance)
      %th= model_class.human_attribute_name(:transport_allowance)
      %th= model_class.human_attribute_name(:medical_allowance)
      %th= model_class.human_attribute_name(:tech_research_allowance)
      %th= model_class.human_attribute_name(:special_allowance)
      %th= model_class.human_attribute_name(:internet_and_telephone)
      %th= model_class.human_attribute_name(:pf_contribution_by_employer)
      %th= model_class.human_attribute_name(:leave_travel_allowance)
      %th= model_class.human_attribute_name(:gross_salary)
      %th= model_class.human_attribute_name(:tds)
      %th= model_class.human_attribute_name(:pf)
      %th= model_class.human_attribute_name(:advance)
      %th= model_class.human_attribute_name(:net_payable)
      %th= model_class.human_attribute_name(:user_id)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @salaries.each do |salary|
      %tr
        %td= link_to salary.id, salary_path(salary)
        %td= salary.name
        %td= salary.basic
        %td= salary.hra
        %td= salary.children_allowance
        %td= salary.transport_allowance
        %td= salary.medical_allowance
        %td= salary.tech_research_allowance
        %td= salary.special_allowance
        %td= salary.internet_and_telephone
        %td= salary.pf_contribution_by_employer
        %td= salary.leave_travel_allowance
        %td= salary.gross_salary
        %td= salary.tds
        %td= salary.pf
        %td= salary.advance
        %td= salary.net_payable
        %td= salary.user_id
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_salary_path(salary), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), salary_path(salary), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_salary_path, :class => 'btn btn-primary'

app/views/salaries/new.html.haml
- model_class = Salary
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/salaries/show.html.haml
- model_class = Salary
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @salary.name
%p
  %strong= model_class.human_attribute_name(:basic) + ':'
  %br
  = @salary.basic
%p
  %strong= model_class.human_attribute_name(:hra) + ':'
  %br
  = @salary.hra
%p
  %strong= model_class.human_attribute_name(:children_allowance) + ':'
  %br
  = @salary.children_allowance
%p
  %strong= model_class.human_attribute_name(:transport_allowance) + ':'
  %br
  = @salary.transport_allowance
%p
  %strong= model_class.human_attribute_name(:medical_allowance) + ':'
  %br
  = @salary.medical_allowance
%p
  %strong= model_class.human_attribute_name(:tech_research_allowance) + ':'
  %br
  = @salary.tech_research_allowance
%p
  %strong= model_class.human_attribute_name(:special_allowance) + ':'
  %br
  = @salary.special_allowance
%p
  %strong= model_class.human_attribute_name(:internet_and_telephone) + ':'
  %br
  = @salary.internet_and_telephone
%p
  %strong= model_class.human_attribute_name(:pf_contribution_by_employer) + ':'
  %br
  = @salary.pf_contribution_by_employer
%p
  %strong= model_class.human_attribute_name(:leave_travel_allowance) + ':'
  %br
  = @salary.leave_travel_allowance
%p
  %strong= model_class.human_attribute_name(:gross_salary) + ':'
  %br
  = @salary.gross_salary
%p
  %strong= model_class.human_attribute_name(:tds) + ':'
  %br
  = @salary.tds
%p
  %strong= model_class.human_attribute_name(:pf) + ':'
  %br
  = @salary.pf
%p
  %strong= model_class.human_attribute_name(:advance) + ':'
  %br
  = @salary.advance
%p
  %strong= model_class.human_attribute_name(:net_payable) + ':'
  %br
  = @salary.net_payable
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @salary.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), salaries_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_salary_path(@salary), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), salary_path(@salary), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :pan
    = f.text_field :pan
  .field
    = f.label :designation
    = f.text_field :designation
  .field
    = f.label :pf
    = f.text_field :pf
  .field
    = f.label :joined_at
    = f.date_select :joined_at
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th Pan
    %th Designation
    %th Pf
    %th Joined at
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.pan
      %td= user.designation
      %td= user.pf
      %td= user.joined_at
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/salary_slip.html.haml
%html
  %head
    :css
      table tr td{border: 1px solid #000000;}
      table{width: 100%;}
      .center {text-align: center;}
      .strong {font-weight:bold;}

%table
  %tr
    %td{:style => "text-align:center"}
      SRIJAN TECHNOLOGIES PVT LTD
      %br
      8A&8E,Vandana Building,11 Tolstoy Road
      %br
      Connaught Place,New Delhi- 110001
  %tr
    %td
      Pay slip For the Month of #{Time.now.strftime('%B %Y')}
  %tr
    %td
      %table
        %tr
          %td Name
          %td
            = @user.name
          %td Date of Joining
          %td
            = @user.joined_at
        %tr
          %td Designation
          %td
            = @user.designation
          %td Department
          %td Not Available!!
        %tr
          %td PF Number
          %td
            = @user.pf
          %td PAN
          %td
            = @user.pan
        %tr
          %td.center.strong{:colspan => 2} Earnings
          %td.center.strong{:colspan => 2} Deductions
        %tr
          %td Description
          %td Amount
          %td Description
          %td Amount
        %tr
          %td BASIC
          %td
            = @salary.basic
          %td TDS
          %td
            = @salary.tds
        %tr
          %td HRA
          %td
            = @salary.hra
          %td TDS
          %td
            = @salary.pf
        %tr
          %td Transport Allowance
          %td
            = @salary.transport_allowance
          %td Advance
          %td
            = @salary.advance
        %tr
          %td Medical Allowance
          %td
            = @salary.medical_allowance
          %td &nbsp;
          %td &nbsp;
        %tr
          %td Children Allowance
          %td
            = @salary.children_allowance
          %td &nbsp;
          %td &nbsp;
        %tr
          %td Technology Research
          %td
            = @salary.tech_research_allowance
          %td &nbsp;
          %td &nbsp;
        %tr
          %td Leave Travel Allowance
          %td
            = @salary.leave_travel_allowance
          %td &nbsp;
          %td &nbsp;
        %tr
          %td Internet and Telephone
          %td
            = @salary.internet_and_telephone
          %td &nbsp;
          %td &nbsp;
        %tr
          %td Special Allowance
          %td
            = @salary.special_allowance
          %td &nbsp;
          %td &nbsp;
        %tr
          %td.strong GROSS PAY
          %td
            = @salary.gross_salary
          %td.strong Net Pay
          %td
            = @salary.net_payable

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Pan:
  = @user.pan
%p
  %b Designation:
  = @user.designation
%p
  %b Pf:
  = @user.pf
%p
  %b Joined at:
  = @user.joined_at

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path